buildServer:
 stage: build
 script:
  - cd UltimateTicTacToe
  - dotnet build
 only:
  - merge-requests
  
buildAngular:
 stage: build
 script:
  - cd UltimateTicTacToe/ClientApp
  - npm install
  - npm run build
 only:
  - merge-requests

testServer:
 stage: test
 script:
  - cd UltimateTicTacToeTests
  - dotnet test
 only:
  - merge-requests

testAngular:
 stage: test
 script:
  - cd UltimateTicTacToe/ClientApp
  - npm install
  - npm run test
 only:
  - merge-requests

produceArtifact:
 stage: deploy
 script:
  - cd UltimateTicTacToe
  - dotnet build
  - dotnet publish -c Release -r ubuntu.18.04-x64
 only:
  - merge-requests