buildServer:
 stage: build
 script:
  - cd UltimateTicTacToe
  - dotnet build
  
buildAngular:
 stage: build
 script:
  - cd UltimateTicTacToe/ClientApp
  - npm install
  - npm run build

testServer:
 stage: test
 script:
  - cd UltimateTicTacToeTests
  - dotnet test

testAngular:
 stage: test
 script:
  - cd UltimateTicTacToe/ClientApp
  - npm run test

produceArtifact:
 stage: deploy
 script:
  - cd UltimateTicTacToe
  - dotnet publish -c Release -r ubuntu.18.04-x64
 only:
  - master
  