buildServer:
 stage: build
 script:
  - cd UltimateTicTacToe
  - dotnet build
 only:
  - master
  
buildAngular:
 stage: build
 script:
  - cd UltimateTicTacToe/ClientApp
  - npm install
  - npm run build
 only:
  - master

testServer:
 stage: test
 script:
  - cd UltimateTicTacToeTests
  - dotnet test
 only:
  - master

testAngular:
 stage: test
 script:
  - cd UltimateTicTacToe/ClientApp
  - npm install
  - npm run test
 only:
  - master

produceArtifact:
 stage: deploy
 script:
  - cd UltimateTicTacToe
  - dotnet restore
  - dotnet publish -c Release -r ubuntu.18.04-x64
  - bash
  - sshpass -e ypb14146@cafe.cis.strath.ac.uk
 only:
  - master