buildServer:
 stage: build
 script:
  - cd UltimateTicTacToe
  - dotnet build
 only:
  - master
  
buildAngular:
 stage: build
 script:
  - cd UltimateTicTacToe/ClientApp
  - npm install
  - npm run build
 only:
  - master

testServer:
 stage: test
 script:
  - cd UltimateTicTacToeTests
  - dotnet test
 only:
  - master

testAngular:
 stage: test
 script:
  - cd UltimateTicTacToe/ClientApp
  - npm install
  - npm run test
 only:
  - master
  